<?php

namespace Emagister\BannersBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdvertiserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertiserRepository extends EntityRepository
{
}